server:
  port: 8761
spring:
  application:
    name: faith-client
eureka:
  client:
    service-url:
      defaultZone: http://server01:8000/eureka/,http://server02:9000/eureka/
  instance:
    instance-id: ${spring.application.name}:${server.port}

